taxiapp/config/routes.rb
Rails.application.routes.draw do
  resources :profiles, only: [:edit, :update]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'page#home'

  get 'page/viaja'

  get 'page/conduce'

  get 'page/contacto'

end

taxiapp/app/models/profile.rb
class Profile < ActiveRecord::Base

  belongs_to :user  

  def full_name

      self.first_name + " " + self.last_name

  end

end

taxiapp/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_one :profile
          enum role: [:user, :driver, :admin]
          after_initialize :set_default_role


  def set_default_role
    self.role ||= :user
  end

  def default_profile

    if self.profile.nil?
      profile = Profile.new
      profile.user = self
      profile.save
     self.save      
    end

   self.profile

  end

  def friendly_name

    if self.default_profile.first_name.nil?
      self.email
    else
      self.profile.full_name
    end
  end



         
end

taxiapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

taxiapp/app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def viaja
  end

  def conduce
  end

  def contacto
  end
end

taxiapp/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update

    respond_to do |format|

      if @profile.update(profile_params)

        format.html { redirect_to root_url, notice: 'Profile was successfully updated.' }

        format.json { render :show, status: :ok, location: @profile }

      else

        format.html { render :edit }

        format.json { render json: @profile.errors, status: :unprocessable_entity }

      end

    end

  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :born_at, :user_id)
    end
end

taxiapp/app/helpers/application_helper.rb
module ApplicationHelper
end

taxiapp/app/helpers/page_helper.rb
module PageHelper
end

taxiapp/app/helpers/profiles_helper.rb
module ProfilesHelper
end

taxiapp/app/views/layouts/_authentication.html.erb
<p class="navbar-text navbar-right">

  <% if current_user %>

      Signed in as <%= link_to current_user.friendly_name, edit_profile_path(current_user.default_profile), class: "navbar-link" %>

      <%= " | " %>

      <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "navbar-link" %>

  <% else %>

      <%= link_to "Sign in", new_user_session_path, class: "navbar-link" %>

  <% end %>

</p>

taxiapp/app/views/layouts/_menu.html.erb
<li><%= link_to "Viaja", page_viaja_path  %></li>
<li><%= link_to "Conduce", page_conduce_path  %></li>
<li><%= link_to "Contactanos", page_contacto_path  %></li>

taxiapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Taxiapp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
          <%= render 'layouts/authentication' %>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Taxiapp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
                <%= render 'layouts/menu' %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
                <%= render 'layouts/menu' %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

taxiapp/app/views/page/conduce.html.erb
<h1>Page#conduce</h1>
<p>Find me in app/views/page/conduce.html.erb</p>

taxiapp/app/views/page/contacto.html.erb
<h1>Page#contacto</h1>
<p>Find me in app/views/page/contacto.html.erb</p>

taxiapp/app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

taxiapp/app/views/page/viaja.html.erb
<h1>Page#viaja</h1>
<p>Find me in app/views/page/viaja.html.erb</p>

taxiapp/app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>

  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :first_name %>

    <%= f.input :last_name %>

    <%= f.input :born_at, as: :date %>

  </div>

  <div class="form-actions">

    <%= f.button :submit %>

  </div>

<% end %>

taxiapp/app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

taxiapp/app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Born at</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.born_at %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

taxiapp/app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

taxiapp/app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
  <strong>Born at:</strong>
  <%= @profile.born_at %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>